language: csharp
dotnet: 2.0.0
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
  - osx
sudo: false
install:
  - dotnet restore
script:
  - chmod +x ./test
  - ./test
